added same test Vacancy and Employer
TatsianaKazachenka/HeadHunter pull request #2
Opened 2021-03-08 19:36 UTC by TatsianaKazachenka

2021-03-11 08:21 UTC, vchesnakoutest requested changes
please make fixes

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +    public EmployersList getCountOpenVacancies(String search, String area,String withVacancies) {
String area,String withVacancies - пробел после запятой добавь

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/VacancyAdapter.java
> +                                                        String order_by, String period, String page){
currency_code - currencyCode
order_by - orderBy

follow java naming convention

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/VacancyAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
можно писать:
Map<String, String> params = new HashMap<>();

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
можно писать:
... = new HashMap<>();

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
можно писать:
... = new HashMap<>();

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
можно писать:
... = new HashMap<>();

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +        return list;
можно просто:
return new Gson().fromJson(body, Employer.class);

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/adapters/VacancyAdapter.java
> +        return list;
тоже делай сразу return

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/objects/EmployersList.java
> +    int per_page;
perPage + используй @SerializedName

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +            log.info(String.format("Waiting for a window to appear"));
тут лишний String.format

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +        log.info(String.format("Scrolling by element"));
тут лишний String.format

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public void scrolling(WebElement element) throws InterruptedException {
scrollToElement или moveToElement

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +        Thread.sleep(500);
оставь коммент зачем тут слип

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
на будущее:
можно такие екзекьюторы выносить в отдельный пакет utils > JavaScriptUtils класс. Делать статический метод, который будет принимать один параметр для того, какой скрипт выполнять, а второй для элемента.

и тут просто вызывать: JavaScriptUtils.executeJavaScript("arguments[0].scrollIntoView(true), element)

либо в том же классе cделать метод moveToElementUsingJS и тут просто вызывать: JavaScriptUtils.moveToElementUsingJS(element)

пока можно оставить как есть

2021-03-11 08:21 UTC, vchesnakoutest commented on src/main/java/pages/EmployerPage.java
> +        WebElement selectEmployer = blockEmployers.get(2).findElement(By.tagName(EMPLOYER_NAME));
blockEmployers.get(2) - может передавать "2" как параметр ?

2021-03-11 08:21 UTC, vchesnakoutest commented on src/test/java/tests/EmployerTest.java
> +        Assert.assertEquals(listAPI.getSiteUrl().replace("https://", "").replace("http://", ""), listUI.getSiteUrl().replace("https://", "").replace("http://", ""));
на будущее:
можно сделать сделать статический метод в утилитном классе, который будет обрабатывать урлы (getFormattedUrl(String url) например)

пока можно оставить так

2021-03-12 10:56 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +    public EmployersList getCountOpenVacancies(String search, String area,String withVacancies) {
done

2021-03-12 10:57 UTC, TatsianaKazachenka commented on src/main/java/adapters/VacancyAdapter.java
> +                                                        String order_by, String period, String page){
done

2021-03-12 10:58 UTC, TatsianaKazachenka commented on src/main/java/adapters/VacancyAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
done

2021-03-12 10:58 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
done

2021-03-12 10:59 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
done

2021-03-12 10:59 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
done

2021-03-12 10:59 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +        return list;
done

2021-03-12 11:00 UTC, TatsianaKazachenka commented on src/main/java/adapters/VacancyAdapter.java
> +        return list;
done

2021-03-12 11:01 UTC, TatsianaKazachenka commented on src/main/java/objects/EmployersList.java
> +    int per_page;
done

2021-03-12 11:02 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +            log.info(String.format("Waiting for a window to appear"));
done

2021-03-12 11:02 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +        log.info(String.format("Scrolling by element"));
done

2021-03-12 11:03 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public void scrolling(WebElement element) throws InterruptedException {
done

2021-03-12 11:12 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +        Thread.sleep(500);
done

2021-03-12 11:15 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
done?

2021-03-12 11:15 UTC, TatsianaKazachenka commented on src/main/java/pages/EmployerPage.java
> +        WebElement selectEmployer = blockEmployers.get(2).findElement(By.tagName(EMPLOYER_NAME));
done

2021-03-12 11:23 UTC, TatsianaKazachenka commented on src/test/java/tests/EmployerTest.java
> +        Assert.assertEquals(listAPI.getSiteUrl().replace("https://", "").replace("http://", ""), listUI.getSiteUrl().replace("https://", "").replace("http://", ""));
done

2021-03-12 12:42 UTC, vchesnakoutest approved these changes
well good!

2021-03-12 15:14 UTC, merged