Feature branch 2
TatsianaKazachenka/HeadHunter pull request #3
Opened 2021-03-11 12:18 UTC by TatsianaKazachenka

2021-03-13 11:11 UTC, vchesnakoutest requested changes

2021-03-13 11:11 UTC, vchesnakoutest commented on .circleci/config.yml
> +      #          command: chmod 777 src/test/resources/webdrivers/linux/chromedriver
эту часть можно удалить, мы ее не используем, т.к. ранаем тесты через webdrivermanager

2021-03-13 11:11 UTC, vchesnakoutest commented on pom.xml
> +        </dependency>
эта зависимость за что отвечает ?

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
= new HashMap<>

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/constants/ICommonConstants.java
> +    String HEADER = "[a-zA-Zа-яА-Я«»]";
HEADER_PATTERN или что-то похожее

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public String getNameButtonCreateResume() {
getCreateResumeButtonName

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +            AllureUtils.takeScreenshot(driver);
на будущее: можно ещё как вариант поместить takeScreenshot в TestListener на действие OnTestFailure, тогда нам не надо будет его в каждом методе вызывать. Пока можно оставить так.

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public boolean isSwitchSearch() {
isSwitchSearchDisplayed или что-то похожее

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/EmployerPage.java
> +    public String getIdEmployer(int index) {
getEmployerIdByIndex

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/EmployerPage.java
> +    public String isSwitchLanguage() {
можно просто switchLanguage

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/EmployerPage.java
> +            log.info(ex.getMessage());
log.error я бы в таких случаях ставил

2021-03-13 11:11 UTC, vchesnakoutest commented on src/main/java/pages/VacancyPage.java
> +    public String getIdVacancy(int index) {
getVacancyIdByIndex

2021-03-14 18:10 UTC, TatsianaKazachenka commented on .circleci/config.yml
> +      #          command: chmod 777 src/test/resources/webdrivers/linux/chromedriver
done

2021-03-14 18:10 UTC, TatsianaKazachenka commented on pom.xml
> +        </dependency>
done

2021-03-14 18:11 UTC, TatsianaKazachenka commented on src/main/java/adapters/EmployerAdapter.java
> +        Map<String, String> params = new HashMap<String, String>();
done

2021-03-14 18:11 UTC, TatsianaKazachenka commented on src/main/java/constants/ICommonConstants.java
> +    String HEADER = "[a-zA-Zа-яА-Я«»]";
done

2021-03-14 18:12 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public String getNameButtonCreateResume() {
done

2021-03-14 18:14 UTC, TatsianaKazachenka commented on src/main/java/pages/AdvancedVacancyPage.java
> +    public boolean isSwitchSearch() {
done

2021-03-14 18:14 UTC, TatsianaKazachenka commented on src/main/java/pages/EmployerPage.java
> +    public String getIdEmployer(int index) {
done

2021-03-14 18:15 UTC, TatsianaKazachenka commented on src/main/java/pages/EmployerPage.java
> +    public String isSwitchLanguage() {
done

2021-03-14 18:16 UTC, TatsianaKazachenka commented on src/main/java/pages/EmployerPage.java
> +            log.info(ex.getMessage());
done

2021-03-14 19:48 UTC, vchesnakoutest approved these changes

2021-03-15 08:13 UTC, merged